from typing import Final

CHANNEL_NAMES_MAGIC: Final = b"CNAM"
PATTERN_NAMES_MAGIC: Final = b"PNAM"

BLOCK_MAGIC_BYTES: Final = 4
BLOCK_LENGTH_BYTES: Final = 4

CHANNEL_NAME_BYTES: Final = 20
PATTERN_NAME_BYTES: Final = 32

HISTORY_COUNT_BYTES: Final = 2
HISTORY_ENTRY_BYTES: Final = 8
