from typing import Final

EXTENSION: Final = ".it"
INSTRUMENT_EXTENSION: Final = ".iti"

MAGIC_MODULE: Final = b"IMPM"
MAGIC_SAMPLE: Final = b"IMPS"
MAGIC_INSTRUMENT: Final = b"IMPI"

CREATED_WITH: Final = 0x0214
COMPATIBLE_WITH: Final = 0x0214
DOUBLED_COMPRESSION: Final = 0x0215
