from typing import Final

from trackmod.spec.pitch import NOTE_COUNT, NOTES_PER_OCTAVE
from trackmod.spec.width import NIBBLE_BITS, NIBBLE_MAX

OCTAVE_SHIFT: Final = NIBBLE_BITS
SEMITONE_MASK: Final = NIBBLE_MAX

BASE_NOTE: Final = NOTES_PER_OCTAVE

MIN_NOTE: Final = BASE_NOTE
MAX_NOTE: Final = NOTE_COUNT - 1

CANONICAL_OCTAVES: Final = 8
CANONICAL_MIN_NOTE: Final = BASE_NOTE
CANONICAL_MAX_NOTE: Final = BASE_NOTE + CANONICAL_OCTAVES * NOTES_PER_OCTAVE - 1
