from typing import Final

from trackmod.spec.grid import MIN_CHANNELS
from trackmod.spec.levels import MAX_VOLUME
from trackmod.spec.width import BYTE_MAX, DOUBLE_WORD_MAX, WORD_MAX
from trackmod.trackers.s3m.spec.orders import ORDER_SEPARATOR
from trackmod.trackers.s3m.spec.sizes import CHANNELS_STORED

CANONICAL_MAX_CHANNELS: Final = 16
STRUCTURAL_MAX_CHANNELS: Final = CHANNELS_STORED

CANONICAL_MAX_PATTERNS: Final = 100
STRUCTURAL_MAX_PATTERNS: Final = ORDER_SEPARATOR

CANONICAL_MAX_ORDERS: Final = BYTE_MAX
STRUCTURAL_MAX_ORDERS: Final = WORD_MAX

PATTERN_ROWS: Final = 64

CANONICAL_MAX_SAMPLES: Final = 99
STRUCTURAL_MAX_SAMPLES: Final = BYTE_MAX

CANONICAL_MAX_SAMPLE_FRAMES: Final = 64_000
STRUCTURAL_MAX_SAMPLE_FRAMES: Final = DOUBLE_WORD_MAX

CANONICAL_MAX_SAMPLE_RATE: Final = WORD_MAX
STRUCTURAL_MAX_SAMPLE_RATE: Final = DOUBLE_WORD_MAX

MAX_SAMPLE_VOLUME: Final = MAX_VOLUME

MAX_GLOBAL_VOLUME: Final = MAX_VOLUME
MAX_MIX_VOLUME: Final = 127

MIN_SPEED: Final = 1
MAX_SPEED: Final = BYTE_MAX
MIN_TEMPO: Final = 32
MAX_TEMPO: Final = BYTE_MAX

MAX_VOLUME_PANNING: Final = MAX_VOLUME

PAN_MAX: Final = 15
POSITION_MAX: Final = 128

MIN_CHANNEL_COUNT: Final = MIN_CHANNELS
MAX_BREAK_ROW: Final = PATTERN_ROWS - 1
