from typing import Final

FILE_HEADER_BYTES: Final = 0x60
INSTRUMENT_RECORD_BYTES: Final = 80

PARAGRAPH_BYTES: Final = 16
PARAPOINTER_BYTES: Final = 2
PATTERN_LENGTH_BYTES: Final = 2
ORDER_BYTES: Final = 1

NAME_BYTES: Final = 28
FILENAME_BYTES: Final = 12

CHANNELS_STORED: Final = 32
