from typing import Final

from trackmod.spec.width import BITS_PER_BYTE

FILE_HEADER_BYTES: Final = 0x60
INSTRUMENT_RECORD_BYTES: Final = 80

PARAGRAPH_BYTES: Final = 16
PARAPOINTER_BYTES: Final = 2
PARAPOINTER_BITS: Final = BITS_PER_BYTE * PARAPOINTER_BYTES
WAVEFORM_POINTER_BITS: Final = PARAPOINTER_BITS + BITS_PER_BYTE
PATTERN_LENGTH_BYTES: Final = 2
ORDER_BYTES: Final = 1

NAME_BYTES: Final = 28
FILENAME_BYTES: Final = 12

CHANNELS_STORED: Final = 32
