from typing import Final

from trackmod.trackers.amiga.spec.sizes import (
    MODULE_NAME_BYTES,
    ORDER_TABLE_BYTES,
    SAMPLE_RECORD_BYTES,
)

SAMPLE_SLOTS: Final = 15
SAMPLE_TABLE_BYTES: Final = SAMPLE_SLOTS * SAMPLE_RECORD_BYTES

SEQUENCE_BYTES: Final = 2 + ORDER_TABLE_BYTES

FILE_HEADER_BYTES: Final = MODULE_NAME_BYTES + SAMPLE_TABLE_BYTES + SEQUENCE_BYTES
