from typing import Final

from trackmod.spec.width import BYTE_MAX, DECIMAL_BYTE_MAX
from trackmod.trackers.mod.spec.sizes import SAMPLE_SLOTS

CANONICAL_CHANNELS: Final = 4
EXTENDED_MIN_CHANNELS: Final = 1
EXTENDED_MAX_CHANNELS: Final = 32
STRUCTURAL_MAX_CHANNELS: Final = DECIMAL_BYTE_MAX

TAGGED_MAX_PATTERNS: Final = 64
EXTENDED_MAX_PATTERNS: Final = BYTE_MAX + 1

MAX_SAMPLES: Final = SAMPLE_SLOTS

LOOP_BEGIN_UNIT: Final = 2

MIN_EFFECT_SPEED: Final = 1
MAX_EFFECT_SPEED: Final = 0x1F
MIN_EFFECT_TEMPO: Final = 0x20
MAX_EFFECT_TEMPO: Final = BYTE_MAX
