from typing import Final

from trackmod.spec.width import BYTE_MAX, WORD_MAX
from trackmod.trackers.mod.spec.periods import FINETUNE_RATES
from trackmod.trackers.mod.spec.sizes import ORDER_TABLE_BYTES, SAMPLE_SLOTS, WORD_BYTES

CANONICAL_CHANNELS: Final = 4
EXTENDED_MIN_CHANNELS: Final = 1
EXTENDED_MAX_CHANNELS: Final = 32

TAGGED_MAX_PATTERNS: Final = 64
CANONICAL_MAX_PATTERNS: Final = 128
EXTENDED_MAX_PATTERNS: Final = BYTE_MAX + 1

MAX_ORDERS: Final = ORDER_TABLE_BYTES

PATTERN_ROWS: Final = 64

MAX_SAMPLES: Final = SAMPLE_SLOTS
MAX_SAMPLE_FRAMES: Final = WORD_MAX * WORD_BYTES

MIN_SAMPLE_RATE: Final = min(FINETUNE_RATES)
MAX_SAMPLE_RATE: Final = max(FINETUNE_RATES)

MIN_EFFECT_SPEED: Final = 1
MAX_EFFECT_SPEED: Final = 0x1F
MIN_EFFECT_TEMPO: Final = 0x20
MAX_EFFECT_TEMPO: Final = BYTE_MAX

MAX_BREAK_ROW: Final = PATTERN_ROWS - 1
