from typing import Final

MODULE_NAME_BYTES: Final = 20
NAME_BYTES: Final = 22

SAMPLE_SLOTS: Final = 31
SAMPLE_RECORD_BYTES: Final = 30
SAMPLE_TABLE_OFFSET: Final = MODULE_NAME_BYTES
SAMPLE_TABLE_BYTES: Final = SAMPLE_SLOTS * SAMPLE_RECORD_BYTES

ORDER_TABLE_BYTES: Final = 128
SEQUENCE_BYTES: Final = 134

FILE_HEADER_BYTES: Final = MODULE_NAME_BYTES + SAMPLE_TABLE_BYTES + SEQUENCE_BYTES

WORD_BYTES: Final = 2
